# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77a39e66e47fca46d2645b82f6380d8d824e1fe7bb913a40c359017add4ee065e291d950148d8f2022e2ef9e5e2066644d583850e6b9e9d88ce263b679a6a41a

test:
  secret_key_base: 2d400b0185ebb86b70804d109b67e067efbcdb05c90b5c0fb1830dae2e4beaf2e2d1d43199dbcbe65196d8efe3c651bcba0a1d310a771998ba13ab61a7400679

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
